CREATE TABLE IF NOT EXISTS users (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 username VARCHAR(30) NOT NULL UNIQUE,
 email VARCHAR(254) NOT NULL UNIQUE,
 name VARCHAR(100) NOT NULL,
 password_hash VARCHAR(255) NOT NULL,
 security_question VARCHAR(200) NOT NULL,
 security_answer_hash VARCHAR(255) NOT NULL,
 session_version INT NOT NULL DEFAULT 0,
 refresh_hash CHAR(64) NULL,
 reset_hash CHAR(64) NULL,
 reset_expires_at DATETIME(6) NULL,
 created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
 deleted_at DATETIME(6) NULL,
 CHECK (CHAR_LENGTH(username) BETWEEN 3 AND 30),
 CHECK (CHAR_LENGTH(name) BETWEEN 2 AND 100)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS categories (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 name VARCHAR(100) NOT NULL UNIQUE,
 description VARCHAR(255) NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS suppliers (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 name VARCHAR(100) NOT NULL,
 cnpj CHAR(14) NOT NULL UNIQUE,
 active BOOLEAN NOT NULL DEFAULT TRUE,
 created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS supplier_categories (
 supplier_id BIGINT NOT NULL,
 category_id BIGINT NOT NULL,
 PRIMARY KEY (supplier_id, category_id),
 FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE,
 FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS products (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 name VARCHAR(160) NOT NULL,
 unit VARCHAR(10) NOT NULL DEFAULT 'un',
 active BOOLEAN NOT NULL DEFAULT TRUE,
 created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 INDEX idx_product_name (name)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS supplier_products (
 supplier_id BIGINT NOT NULL,
 product_id BIGINT NOT NULL,
 price DECIMAL(12,2) NOT NULL,
 stock INT NOT NULL DEFAULT 0,
 active BOOLEAN NOT NULL DEFAULT TRUE,
 PRIMARY KEY (supplier_id, product_id),
 FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE,
 FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT,
 CHECK (price >= 0),
 CHECK (stock >= 0)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS lists (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 user_id BIGINT NOT NULL,
 name VARCHAR(100) NOT NULL,
 created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
 deleted_at DATETIME(6) NULL,
 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
 CHECK (CHAR_LENGTH(name) BETWEEN 1 AND 100),
 INDEX idx_user_created (user_id, created_at DESC)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS list_items (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 list_id BIGINT NOT NULL,
 product_id BIGINT NOT NULL,
 quantity INT NOT NULL,
 created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 FOREIGN KEY (list_id) REFERENCES lists(id) ON DELETE CASCADE,
 FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT,
 UNIQUE (list_id, product_id),
 CHECK (quantity BETWEEN 1 AND 9999)
) ENGINE=InnoDB;
