from typing import ContextManager, Protocol


class Store(Protocol):
    def transaction(self) -> ContextManager: ...
    def categories(self) -> list[dict]: ...
    def products(self, query: str) -> list[dict]: ...
    def catalog(self, items: list[dict], category_id: int | None = None) -> tuple: ...
    def lists(self, user_id: int, page: int, query: str) -> dict: ...
    def get_list(self, user_id: int, list_id: int) -> dict: ...
    def save_list(self, user_id: int, data: dict, list_id: int | None = None) -> dict: ...
    def delete_list(self, user_id: int, list_id: int) -> None: ...


class Security(Protocol):
    def hash(self, value: str) -> str: ...
    def verify(self, value: str, hashed: str) -> bool: ...
    def digest(self, value: str) -> str: ...
    def tokens(self, user: dict) -> dict: ...
    def decode(self, token: str, kind: str) -> dict: ...
